# Copyright 2024 tison <wander4096@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "logforth"

authors = ["tison <wander4096@gmail.com>"]
description = "A versatile and extensible logging implementation."
edition = "2021"
homepage = "https://github.com/tisonkun/logforth"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tisonkun/logforth"
rust-version = "1.71.0"
version = "0.4.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docs"]

[features]
fastrace = ["dep:fastrace"]
file = ["dep:crossbeam-channel", "dep:parking_lot", "dep:time"]
json = ["dep:serde_json", "dep:serde"]
no-color = ["colored/no-color"]
opentelemetry = [
  "dep:opentelemetry",
  "dep:opentelemetry-otlp",
  "dep:opentelemetry_sdk",
]

[dependencies]
anyhow = { version = "1.0" }
colored = { version = "2.1" }
crossbeam-channel = { version = "0.5", optional = true }
fastrace = { version = "0.6", optional = true }
humantime = { version = "2.1" }
log = { version = "0.4", features = ["std", "kv_unstable"] }
opentelemetry = { version = "0.24", features = ["logs"], optional = true }
opentelemetry-otlp = { version = "0.17", features = [
  "logs",
  "grpc-tonic",
], optional = true }
opentelemetry_sdk = { version = "0.24", features = [
  "logs",
  "rt-tokio",
], optional = true }
parking_lot = { version = "0.12", optional = true }
paste = { version = "1.0" }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
time = { version = "0.3", features = [
  "formatting",
  "parsing",
], optional = true }

[[example]]
name = "fn_layout_filter"
path = "examples/fn_layout_filter.rs"

[[example]]
name = "simple_stdio"
path = "examples/simple_stdio.rs"

[[example]]
name = "no_color_stdio"
path = "examples/no_color_stdio.rs"
required-features = ["no-color"]

[[example]]
name = "json_stdio"
path = "examples/json_stdio.rs"
required-features = ["json"]

[[example]]
name = "rolling_file"
path = "examples/rolling_file.rs"
required-features = ["file", "json"]
