# Copyright 2024 FastLabs Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "logforth"

authors = ["FastLabs Developers"]
description = "A versatile and extensible logging implementation."
edition = "2021"
homepage = "https://github.com/fast/logforth"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/fast/logforth"
rust-version = "1.71.0"
version = "0.9.1"

categories = ["development-tools::debugging"]
keywords = ["logging", "log", "opentelemetry", "fastrace"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docs"]

[features]
fastrace = ["dep:fastrace"]
json = ["dep:serde_json", "dep:serde", "jiff/serde"]
no-color = ["colored/no-color"]
opentelemetry = [
  "dep:opentelemetry",
  "dep:opentelemetry-otlp",
  "dep:opentelemetry_sdk",
]
rolling_file = ["dep:crossbeam-channel", "dep:parking_lot"]

[dependencies]
anyhow = { version = "1.0" }
colored = { version = "2.1" }
jiff = { version = "0.1.5" }
log = { version = "0.4", features = ["std", "kv_unstable"] }
paste = { version = "1.0" }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.8"
tempfile = "3.12"

## Rolling file dependencies
[dependencies.crossbeam-channel]
optional = true
version = "0.5"

[dependencies.parking_lot]
optional = true
version = "0.12"

## Fastrace dependencies
[dependencies.fastrace]
optional = true
version = "0.6"

## Opentelemetry dependencies
[dependencies.opentelemetry]
features = ["logs"]
optional = true
version = "0.24"

[dependencies.opentelemetry-otlp]
features = ["logs", "grpc-tonic", "http-json", "http-proto"]
optional = true
version = "0.17"

[dependencies.opentelemetry_sdk]
features = ["logs", "rt-tokio"]
optional = true
version = "0.24"

## Examples
[[example]]
name = "simple_stdio"
path = "examples/simple_stdio.rs"

[[example]]
name = "json_stdio"
path = "examples/json_stdio.rs"
required-features = ["json"]

[[example]]
name = "rolling_file"
path = "examples/rolling_file.rs"
required-features = ["rolling_file", "json"]

[[example]]
name = "fn_layout_filter"
path = "examples/fn_layout_filter.rs"
